export const ADD_FRIEND="ADD_FRIEND"
export const STAR_FRIEND="STAR_FRIEND"
export const DELETE_FRIEND="DELETE_FRIEND"
export const REQUEST_FRIEND = 'REQUEST_FRIEND'
export const RECEIVE_FRIEND = 'RECEIVE_FRIEND'
export const INVALIDATE_FRIEND = 'INVALIDATE_FRIEND'

export const ADD_TO_CART = 'ADD_TO_CART'
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'